---
title: "Chocolate"
author: "Danielle Marichal"
date: "2026-10-02"
output: html_document
---

```{r}
##Estimate the proportion of people like chocolate
#Specifying a prior for a proportion
#You can find the best Beta prior to use in this case by specifying that the median (50% percentile) of the prior is 0.85, that the 99.999% percentile is 0.95, and that the 0.001% percentile is 0.60
```

```{r}
if (!requireNamespace("LearnBayes", quietly = TRUE)) {install.packages("LearnBayes", repos = "https://r-project.org")}
library("LearnBayes")
#We believe the median of the prior is 0.85
quantile1<-list(p=0.5, x=0.85)
#We believe the 99.999th percentile of the prior is 0.95
quantile2<-list(p=0.99999,x=0.95)
#We believe the 0.001st percentile of the prior is 0.60
quantile3<-list(p=0.00001,x=0.60)
#We can use the findBeta() function below to find the most appropriate Beta prior to use.
findBeta<-function(quantile1,quantile2,quantile3)
#Find the quantiles specified by quantile1 and quantile2 and quantile3
quantile1_p<-quantile1[[1]];quantile1_q<-quantile1[[2]]
quantile2_p<-quantile2[[1]];quantile2_q<-quantile2[[2]]
quantile3_p<-quantile3[[1]];quantile3_q<-quantile3[[2]]
#Find the beta prior using quantile1 and quantile2
priorA<-beta.select(quantile1,quantile2)
priorA_a<-priorA[1];priorA_b<-priorA[2]
#Find the beta prior using quantile1 and quantile3
priorB<-beta.select(quantile1,quantile3)
priorB_a<-priorB[1];priorB_b<-priorB[2]
#Find the best possible beta prior
diff_a<-abs(priorA_a - priorB_a)
diff_b<-abs(priorA_b - priorB_b)
step_a<-diff_a / 100; step_b<-diff_b / 100
if (priorA_a<priorB_a){start_a<-priorA_a;end_a<-priorB_a}else{start_a<-priorB_a;end_a<-priorA_a}
if (priorA_b < priorB_b){start_b<-priorA_b; end_b<- priorB_b }else{ start_b<-priorB_b; end_b<-priorA_b}
steps_a<-seq(from=start_a,to=end_a,length.out=1000)
steps_b<-seq(from=start_b,to=end_b,length.out=1000)
max_error<-10000000000000000000
best_a<-0; best_b<-0
for (a in steps_a) {
for (b in steps_b) {
priorC_q1 <- qbeta(quantile1_p, a, b)
priorC_q2 <- qbeta(quantile2_p, a, b)
priorC_q3 <- qbeta(quantile3_p, a, b)
priorC_error <- abs(priorC_q1 - quantile1_q) +abs(priorC_q2 - quantile2_q) + abs(priorC_q3 - quantile3_q)
if (priorC_error < max_error) {max_error <-priorC_error
best_a <- a
best_b <- b}}} 
print(paste("The best beta prior has a=",best_a,"b=",best_b))
findBeta(quantile1,quantile2,quantile3)
#This tells us that the most appropriate prior to use for the proportion of individuals who like chocolate is a Beta prior with a=52.22 and b=9.52, that is, a Beta(52.22, 9.52) prior. We can plot the prior density by using the “curve” function:
curve(dbeta(x,52.22,9.52105105105105))
##Calculating the Likelihood Function for a Proportion
calcLikelihoodForProportion<-function(successes, total){curve(dbinom(successes,total,x))}
calcLikelihoodForProportion(45, 50)
#Calculating the Posterior Distribution for a Proportion
calcPosteriorForProportion <- function(successes, total, a, b){
likelihood_a = successes + 1; likelihood_b = total - successes + 1
posterior_a = a + successes;  posterior_b = b + total - successes
theta = seq(0.005, 0.995, length = 500)
prior = dbeta(theta, a, b)
likelihood = dbeta(theta, likelihood_a, likelihood_b)
posterior  = dbeta(theta, posterior_a, posterior_b)
m = max(c(prior, likelihood, posterior))
plot(theta, posterior, type = "l", ylab = "Density", lty = 2, lwd = 3,main = paste("beta(", a, ",", b, ") prior, B(", total, ",", successes, ") data,","beta(", posterior_a, ",", posterior_b, ") posterior"), ylim = c(0, m), col = "red")
lines(theta, likelihood, lty = 1, lwd = 3, col = "blue")
lines(theta, prior, lty = 3, lwd = 3, col = "green")
legend(x=0.8,y=m, c("Prior", "Likelihood", "Posterior"), lty = c(3, 1, 2),lwd = c(3, 3, 3), col = c("green", "blue", "red"))
calcBetaMode <- function(aa, bb) { BetaMode <- (aa - 1)/(aa + bb - 2); return(BetaMode); }
calcBetaMean <- function(aa, bb) { BetaMean<-(aa)/(aa + bb); return(BetaMean); }
calcBetaSd   <- function(aa, bb) { BetaSd <- sqrt((aa * bb)/(((aa + bb)^2) * (aa + bb + 1))); return(BetaSd); }
prior_mode<- calcBetaMode(a, b)
likelihood_mode<-calcBetaMode(likelihood_a,likelihood_b)
posterior_mode<-calcBetaMode(posterior_a,posterior_b)
prior_mean<- calcBetaMean(a, b)
likelihood_mean<-calcBetaMean(likelihood_a,likelihood_b)
posterior_mean<-calcBetaMean(posterior_a,posterior_b)
prior_sd<-calcBetaSd(a, b)
likelihood_sd<-calcBetaSd(likelihood_a, likelihood_b)
posterior_sd<- calcBetaSd(posterior_a, posterior_b)
print(paste("mode for prior=",prior_mode,", for likelihood=",likelihood_mode,", for posterior=",posterior_mode))
print(paste("mean for prior=",prior_mean,", for likelihood=",likelihood_mean,", for posterior=",posterior_mean))
print(paste("sd for prior=",prior_sd,", for likelihood=",likelihood_sd,", for posterior=",posterior_sd))
}
#To use the “calcPosteriorForProportion()” function, you will first need to copy and paste it into R. It takes four arguments: the number of successes and total sample size in your data set, and the a and b values for your Beta prior. For example, to estimate the proportion of people who like chocolate, you had a Beta(52.22,9.52) prior and had observed in a survey that 45 out of 50 people like chocolate. Therefore, the number of successes is 45, the sample size is 50, and a and b for the prior are 52.22 and 9.52 respectively. Therefore, we can calculate the posterior for the proportion of people who like chocolate, given the data and prior, by typing:
calcPosteriorForProportion(45, 50, 52.22, 9.52)
```

